### ISSUE TITLE
Unable to load virtio_rdmacm.ko due to duplicated exported symbols (owned by rdma_cm)

### ISSUE THREAD

**Issue by fbz-ict** [zrlio/hyv#1]
Following the steps provided in the README file, i got the following error when i try to load virtio_rdmacm.ko

[root]# insmod virtio_rdmacm.ko
insmod: ERROR: could not insert module virtio_rdmacm.ko: Invalid module format

[root]# dmesg
virtio_rdmacm: exports duplicate symbol rdma_accept (owned by rdma_cm)

Module rdma_cm is automatically loaded when the ib_core module is loaded due to the dependence.  Since virtio_rdmacm requires ib_core, i cannot solve the problem by loading virtio_rdmacm first.

To solve this problem, i think i have to manually remove the rdma_cm module. To this end, i have to first remove xprtrdma,ib_iser,rdma_ucm and ib_isert, since they all use rdma_cm module.

After that, i could load virtio_rdmacm.ko. But, the command "ibv_devinfo" returns "No IB devices found".

In the host, i got the following outputs:
[root@localhost qemu-2.2.0]# ./start_guest_rdma 
(process:9849): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
virtio_hyv_device_realize
virtio_hyv_read_config
virtio_rdmacm_device_realize
virtio_rdmacm_set_status - start
virtio_hyv_handle_q
virtio_hyv_set_status - start

Is there anything wrong in my operations (since it seems that mannually removing rdma_cm is not required according to the README)? 
Thx!

**Comment by fbz-ict** [comment]
If i turn on DBG_ALL, i get the following outputs: (the problem seems to be that the device and the driver don't match)

--update---
I changed the NIC to the compatible ConnectX-3 HCA ({713, 4099}). However, after loading the virtmlx4_ib module (insmod virtmlx4_ib.ko), the VM breakdown. Therefore, I have to restart the VM, but  there is nothing recorded in the log file (/var/logs/messages)

[root@....]dmesg
....
[  359.977315] ( 3648/0) init 
[  359.977404] ( 3648/0) virtio_rdmacm_probe 
[  359.977406] ( 3648/0) virtio_rdmacm_init_vqs 
[  359.977539] virtio-pci 0000:00:05.0: irq 45 for MSI/MSI-X
[  359.977569] virtio-pci 0000:00:05.0: irq 46 for MSI/MSI-X
[  370.622562] ( 3668/0) init 
[  370.622574] ( 3668/0) hyv_bus_init 
[  370.622694] ( 3668/0) virtio_hyv_probe 
[  370.622697] ( 3668/0) virtio_hyv_init_vqs 
[  370.622862] virtio-pci 0000:00:04.0: irq 47 for MSI/MSI-X
[  370.622895] virtio-pci 0000:00:04.0: irq 48 for MSI/MSI-X
[  370.622926] virtio-pci 0000:00:04.0: irq 49 for MSI/MSI-X
[  370.623339] ( 3668/0) virtio_hyv_create_event_queue 
[  370.632386] ( irq /0) virtio_hyv_ack_event 
[  370.632390] ( irq /0) virtio_hyv_ack_event add device
[  370.638963] ( 3425/0) add_device host_handle: 0
[  370.638967] ( 3425/0) register_hyv_device 
[  440.670650] ( 3958/0) register_hyv_driver 
[  440.670668] ( 3958/0) hyv_dev_match match { 713, 4103 }
[  440.670671] ( 3958/0) hyv_dev_match id_table { 713, 4099 }

**Comment by PepperJo** [comment]
The rdma_cm module should not be loaded automatically as ib_core is not dependent on it, but the other way around. When I load ib_core (ubuntu 14.04), the following modules are loaded:

```
$ lsmod | grep ib_core
ib_core                87335  0 
ib_addr                18923  1 ib_core
$ lsmod | grep rdma
$
```

If rdma_cm is loaded the error is expected as we provide all these functions from the virtio_rdmacm module.

The problem that the device is not showing up in ibv_devinfo is however not related to rdma_cm, actually you should be able to enumerate devices without rdma_cm resp. you don't need rdma_cm as long as you don't use RoCE/iWARP or need routable IB.

As you figured out the CX-3 Pro is not in the id_table of the driver and thus does not match. Check my latest commit, i added it to virtmlx4. Without a stack trace there is not much we can do to figure out the problem. You can check if it works with the CX-3Pro, otherwise you might want to setup a crash kernel (in the VM) to debug the issue.

**Comment by fbz-ict** [comment]
My guest os is Centos 7, and it seems that the virtmlx4_dma_xx device and ibdev device couldn't be registered properly by calling device_register and ib_register_device, respectively. 

Now, as you suggested, i switch to ubuntu 14.04, now it works. Thanks

**Comment by PepperJo** [comment]
Yes, the problem with Centos and rhel is that they do heavy backporting of the kernel so the kernel version actually does not say anything really compared to vanilla kernels. There is probably some minor differences in the kernel ib_core in newer versions (>13.3 that I tested with) which lead to the panic. If I find some time I will try to add support for newer kernel versions.

**Comment by fbz-ict** [comment]
Great, really looking forward to that!
